export const APP_CONSTANTS = {
  // Authentication
  AUTH: {
    SIGNATURE_MESSAGE_PREFIX: 'Welcome to GeniePay!',
    MAX_SIGNATURE_AGE_MS: 15 * 60 * 1000, // 15 minutes
    SESSION_DURATION_MS: 24 * 60 * 60 * 1000, // 24 hours
    RETRY_ATTEMPTS: 3,
  },

  // Database
  DATABASE: {
    BATCH_SIZE: 100,
    MAX_QUERY_TIMEOUT: 30000, // 30 seconds
    CONNECTION_POOL_SIZE: 10,
  },

  // UI
  UI: {
    TOAST_DURATION: 5000, // 5 seconds
    MODAL_TRANSITION_DURATION: 200, // 200ms
    DEBOUNCE_DELAY: 300, // 300ms
    POLLING_INTERVAL: 30000, // 30 seconds
  },

  // Blockchain
  BLOCKCHAIN: {
    CONFIRMATION_BLOCKS: 1,
    GAS_LIMIT_BUFFER: 1.2, // 20% buffer
    MAX_GAS_PRICE_GWEI: 100,
    TRANSACTION_TIMEOUT: 60000, // 1 minute
  },

  // Validation
  VALIDATION: {
    MIN_PASSWORD_LENGTH: 8,
    MAX_EMAIL_LENGTH: 254,
    MAX_NAME_LENGTH: 100,
    MIN_SALARY_AMOUNT: 0.01,
    MAX_SALARY_AMOUNT: 1000000,
  },

  // Feature Limits
  LIMITS: {
    MAX_EMPLOYEES_PER_USER: 1000,
    MAX_PAYROLL_BATCH_SIZE: 100,
    MAX_FILE_SIZE_MB: 10,
    MAX_UPLOAD_FILES: 5,
  },
} as const

// Error codes
export const ERROR_CODES = {
  // Authentication errors
  AUTH_SIGNATURE_REJECTED: 'AUTH_SIGNATURE_REJECTED',
  AUTH_SIGNATURE_INVALID: 'AUTH_SIGNATURE_INVALID',
  AUTH_SIGNATURE_EXPIRED: 'AUTH_SIGNATURE_EXPIRED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_TERMS_REJECTED: 'AUTH_TERMS_REJECTED',
  AUTH_WALLET_DISCONNECTED: 'AUTH_WALLET_DISCONNECTED',

  // Database errors
  DB_CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
  DB_QUERY_TIMEOUT: 'DB_QUERY_TIMEOUT',
  DB_CONSTRAINT_VIOLATION: 'DB_CONSTRAINT_VIOLATION',
  DB_RECORD_NOT_FOUND: 'DB_RECORD_NOT_FOUND',
  DB_PERMISSION_DENIED: 'DB_PERMISSION_DENIED',

  // Blockchain errors
  BLOCKCHAIN_NETWORK_ERROR: 'BLOCKCHAIN_NETWORK_ERROR',
  BLOCKCHAIN_TRANSACTION_FAILED: 'BLOCKCHAIN_TRANSACTION_FAILED',
  BLOCKCHAIN_INSUFFICIENT_FUNDS: 'BLOCKCHAIN_INSUFFICIENT_FUNDS',
  BLOCKCHAIN_GAS_ESTIMATION_FAILED: 'BLOCKCHAIN_GAS_ESTIMATION_FAILED',
  BLOCKCHAIN_UNSUPPORTED_CHAIN: 'BLOCKCHAIN_UNSUPPORTED_CHAIN',

  // Validation errors
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_WALLET_ADDRESS: 'VALIDATION_INVALID_WALLET_ADDRESS',
  VALIDATION_AMOUNT_TOO_LOW: 'VALIDATION_AMOUNT_TOO_LOW',
  VALIDATION_AMOUNT_TOO_HIGH: 'VALIDATION_AMOUNT_TOO_HIGH',
  VALIDATION_FILE_TOO_LARGE: 'VALIDATION_FILE_TOO_LARGE',
} as const

export type ErrorCode = keyof typeof ERROR_CODES